### ISSUE TITLE
Latest godot engine can't open tps-demo 4.0-dev branch

### ISSUE THREAD

**Issue by T-rvw** [godotengine/tps-demo#107]
I would like to experience godot vulkan version so I downloaded tps-demo in 4.0-dev branch and built a godot engine in master branch. But the editor crashed during importing scene resources.

Any suggestions? I know that is an unstable engine version. I just wanted to get a nice demo to learn about godot vulkan rendering.

**Comment by aaronfranke** [comment]
The demo hasn't been ported yet. The 4.0-dev branch is currently identical to the master of this repo (designed for Godot 3.x).

**Comment by T-rvw** [comment]
@aaronfranke Thanks for your quick reply. Do you have any recommended samples for Godot 4.0+ which uses Vulkan as rendering backend?

**Comment by aaronfranke** [comment]
@T-rvw https://github.com/Calinou/godot-reflection

There aren't many currently. We should have more things ported in the future, but first we want to improve the automatic conversion tools so that the work can be automated. If you are looking to test rendering, another option is to copy the 3D model files from the TPS demo into an empty Godot 4 project.

**Comment by T-rvw** [comment]
Status update:
Latest godot master version has some break changes on scene format so that many scenes got error : "Scene file '%s' appears to be invalid/corrupt.".
See https://github.com/Calinou/godot-reflection/issues/5.

Anyway, it is closer to know there are valid samples based on godot 4.0. I will try to have a look at changes on scene format and know if it is possible to fix them.

**Comment by fire** [comment]
I recently tested this and the godot 4 branch works on godot 4.0 latest.
