### ISSUE TITLE
git lfs Not in a git repository

### ISSUE THREAD

**Issue by demilavagod** [godotengine/tps-demo#115]
When I type type "git lfs track" into git bash it gives me "Not in a git repository". 

Also I have no idea what files to store on it in a UE4 project because they are all of type "uasset", there is no "fbx" or any other type of file? I have tried cloning the repository I am using and it wont clone because it says "This folder contains files. Git can only clone empty folders." and there's only one repository option.

I have no idea what I am doing I was fine using git desktop until it told me that I can't commit files over 100mb. I just want to store my whole UE4 project safely. Someone please help.

**Comment by Calinou** [comment]
This repository is a Godot Engine project, not an Unreal Engine 4 project.

PS: This repository does not use Git LFS anymore. Cloning the repository and importing the project in Godot 3.4 is enough to get it to run.

**Comment by AceTylerCholine** [comment]
The "This folder contains files. Git can only clone empty folders." error is because the folder you're trying to create/clone your repository into (the one currently/about to be on your computer), already exists, and there are files in that folder. So say you have a repository "Calinou/Project" and you're trying to clone it into "C:\Users\Calinou\Documents\Project", you're getting an error because "C:\Users\Calinou\Documents\Project" already exists and there's at least one file in that folder like "C:\Users\Calinou\Documents\Project\ReadMe.txt". If the Git repository is up to date, then just delete or empty the folder already on your computer, then clone again.
