### ISSUE TITLE
Performance is quite slow

### ISSUE THREAD

**Issue by takhimi** [godotengine/tps-demo#17]
Windows 10 64bit
i7 2600k
8gb ram
gtx970
Installed MSI Afterburner to display fps
Compiled Godot 3.1 from git and load the project.

I only get average of 15-25fps

Hopefully this can be improved when 3.1 is released ? Thanks.

**Comment by Akira1San** [comment]
Try to export the game into desktop and test.

**Comment by menip** [comment]
Terrible performance. Linux, Ryzen 7 1700, 16GB 3200MHz RAM, Radeon RX 480 4GB, 1440p monitor @ 144Hz.
With resolution set to native, and all other option disable:
In editor fps
> 2,66,43,5,11,49,58,60,60,61,54,50,53,50,46,40,42,44,49,46,1,36,21

Exported fps
> 2,67,144,144,144,144,81,5,11,41,50,50,45,51,53,2,38,30,27

Where 144 was while in menu.

Huge lag on load, as well as when firing for first time.

**Comment by Calinou** [comment]
I'll close this issue as it's not really actionable as it currently is. Performance will likely be improved in 4.0 if this demo is ported over.

Stuttering when firing for the first time should be fixed by https://github.com/godotengine/tps-demo/pull/43, and there should be less stuttering with flying bullets thanks to https://github.com/godotengine/tps-demo/pull/35.
