### ISSUE TITLE
git consume way too much net and space

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/tps-demo#5]
Total download  1.63gb
original project 839 mb(downloaded)
.git size 832 mb(extra download/waste of net and space)
ultra compressed 7z size for original project 357mb

**Comment by akien-mga** [comment]
I'm sorry but there's nothing we can do, that's not a bug report for Godot but an enhancement request for upstream Git and Git-LFS.

Git keeps various things in the `.git` folder which enables it to be Git and not just a plain copy of a folder. Git LFS apparently also needs to keep a copy of the objects in `.git/lfs/objects` as per #2147, since it's limited by Git checkout.

We'll provide a compressed archive eventually, but until then this size is expected.
